server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/inventory-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: INVENTORY-SERVICE


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true




