server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/order-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ORDER-SERVICE


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true



